### ISSUE TITLE
Please add a "reload wallpapers" option on the right-click context menu

### ISSUE THREAD

**Issue by Beguiled** [rocksdanister/lively#246] opened 2020-12-20 13:01 UTC
**I'm currently running Lively version 1.1.6.0**

**Is your feature request related to a problem? Please describe.**
After playing a few games today I came back to finding my wallpaper (Triangles & Light) had gotten resized to only a portion of my desktop. In addition to that, it was reacting to my mouse in an inverted way. I had to open the Lively UI and use the "Set as wallpaper" option to restore it.

**Describe the solution you'd like**
An option on the taskbar icon to "Reload wallpapers", much like "Close wallpapers" and "Pause wallpapers" provides.

**Describe alternatives you've considered**
N/A

**Additional context**
See this screenshot of how it was rendering on my screen (my mouse was on the bottom right):
![image](https://user-images.githubusercontent.com/7060159/102713909-619c6100-4299-11eb-8cd2-b0f78a9ccc4e.png)

**Comment by rocksdanister** [comment] 2020-12-20 13:17
Can you reliability recreate this bug? I got multiple reports of this bug but I can't recreate it on my system.

**Comment by Beguiled** [comment] 2020-12-20 13:30
I’ll see what I can do. It occurred after playing Minecraft for a few minutes.

**Comment by rocksdanister** [comment] 2020-12-21 11:22
My guess is its the full-screen exclusive mode resolution change event.. the reason I'm confused is - currently wallpaper resizing when display settings changed is disabled due to a unrelated bug:
https://github.com/rocksdanister/lively/blob/d2b4ac5bee24abd910b1428c2a3fb89592cb1cc0/src/livelywpf/livelywpf/Core/SetupDesktop.cs#L622-L633

So something else changing the wallpaper windowsize, I don't think Windows is doing it(?).

>An option on the taskbar icon to "Reload wallpapers", much like "Close wallpapers" and "Pause wallpapers" provides.

I won't do that, its better to fix the root cause instead.

**Comment by Beguiled** [comment] 2020-12-21 12:24
> I won't do that, its better to fix the root cause instead.

I agree. Want me to close this FR then?

**Comment by rocksdanister** [comment] 2020-12-21 13:08
Keep it open, lets see how things turn out; I think I can make a fix with next update.

**Comment by rocksdanister** [comment] 2020-12-24 02:12
You can try the beta build to see if the issue is resolved:
https://github.com/rocksdanister/lively-beta/releases

If this does not work, then I'll either have to verify and correct the wallpaper window size regularly in a loop or subscribe to wallpaper window size changed event and do the same.

**Comment by Beguiled** [comment] 2020-12-24 11:45
I'll see if I cannot get the issue to happen again on the current version. I haven't seen it since reporting, unfortunately.

**Comment by Beguiled** [comment] 2021-01-04 11:26
Hey @rocksdanister I got it to happen again. This time it occurred when my desktop didn't show up until I power-cycled my screen. This is most likely rooted in hardware driver issues, then. However, what I did do when this occurred is turned on debug output. This is what it showed (see the desktop behind the window is only partially covered, and the wallpaper is non-responsive to mouse movement):
![image](https://user-images.githubusercontent.com/7060159/103530551-a279a580-4e55-11eb-8f6d-c75613a2d992.png)

As you can see, the application is working with 1024x768 as the resolution, instead of referring to the actual resolution of the desktop. Perhaps the desktop resolution needs to be polled more often to ensure Lively is using the appropriate resolution at the time.

**Comment by rocksdanister** [comment] 2021-01-04 12:52
>This time it occurred when my desktop didn't show up until I power-cycled my screen.

I don't understand what this means, can you explain?

**Comment by Beguiled** [comment] 2021-01-04 13:09
Yes, of course. I’d booted my PC but the screen remained “off” as if they were not getting any signal from the video card. Knowing I should have been at the log in prompt at that point I powered off my screen and back on again. Then the screen found the connection and I was presented with my Windows login prompt. I logged into Windows and lively started as it is a Startup Item but was operating with a low resolution (1024x768), and was not responsive to my mouse movements. 

Hopefully that helps a bit.

**Comment by rocksdanister** [comment] 2021-01-05 07:40
Looks like 1024x768 is fallback resolution:
https://www.windowsdigitals.com/windows-10-resolution-stuck-at-1024x768-only/

I don't see any display settings changed event firing, I think windows is failing me here :(
Looks like my only option is to periodically check screen and wallpaper parameters.

**Comment by rocksdanister** [comment] 2021-02-06 05:55
Next update changes the screen management code by a lot https://github.com/rocksdanister/lively/pull/293
I think it might have fixed this issue 🤔

**Comment by rocksdanister** [comment] 2021-02-07 14:33
Can you try the latest beta build:
https://github.com/rocksdanister/lively-beta/releases

**Comment by Beguiled** [comment] 2021-02-07 14:49
I just installed it and will let you know if the same issue I had before persists. I saw the improvements you've been making and I have high hopes they'll be better for the application overall.

**Comment by rocksdanister** [comment] 2021-02-27 06:22
How is it so far? 👀

**Comment by Beguiled** [comment] 2021-02-27 11:13
Actually I have not encountered this issue again since your changes were made. At this time I’d say you fixed it! 👍

I’ll start a new issue if it happens again and will attempt to find reproducible steps.

**Comment by rocksdanister** [comment] 2021-02-27 11:36
Great! 
I'll close this issue in that case.

**Closed as completed by rocksdanister** 2021-02-27 11:36 UTC
Labels: enhancement, working on it
