### ISSUE TITLE
Steam cannot connect when Lively running

### ISSUE THREAD

**Issue by Clixs18** [rocksdanister/lively#745] opened 2021-09-22 00:58 UTC
I was opening Steam today, and it said Could not connect to Network. I tried many things to fix this issue. I was reading more articles on how to fix this, and one of them said back round apps. When I closed down Lively Wallpaper, Steam worked great, but when Lively Wallpaper is on in the back round, it would not let me go online with Steam. This is the first time this has happened to me. Please fix this.

**Comment by rocksdanister** [comment] 2021-09-22 01:03
This is not a problem caused by Lively, Lively does not make any system modifications for something like this to happen.

What likely happened is Steam does routine maintenance on tuesday so the service was down..

Closing this for now.. will be reopened if more information is provided showing its caused by Lively.

**Closed as completed by rocksdanister** 2021-09-22 01:03 UTC
Labels: invalid, unable to reproduce, unrelated
