### ISSUE TITLE
Completely Stopped Working After Windows 11 Update 22H2. 

### ISSUE THREAD

**Issue by arthursilvap** [rocksdanister/lively#1915] opened 2023-09-28 23:48 UTC
**Describe the bug**
_After updating my Windows 11, which now has CoPilot (Preview) integrated into the computer, Lively has stopped working entirely. I reinstalled the app from the Microsoft Store, and it worked; however, when I turned my computer on the next day, Lively stopped working again. I have "Animate windows when minimizing and maximizing" enabled, and I have never had an issue in the past - I can not find any solution online, and this only occurred post the Windows update with CoPilot (Preview). I have four monitors._

**Screenshots/Video**
Screenshots won't really help - whenever I click on an image for my wallpaper, nothing happens whatsoever.

**Desktop (please complete the following information):**
Microsoft Windows 11 Pro
10.0.22621 Build 22621

**Additional context**
No additional comments.

**Log file (Important)**
Attached.
[lively_log_20230928_194649.zip](https://github.com/rocksdanister/lively/files/12754648/lively_log_20230928_194649.zip)

**Comment by Styphoryte** [comment] 2023-09-29 21:47
Same issue here as well. I'll attach my log as well. 

**Describe the bug**
After updating my Windows 11, which now has CoPilot (Preview) integrated into the computer, Lively has stopped working entirely. I reinstalled the app from the Microsoft Store, and it worked; however, when I turned my computer on the next day, Lively stopped working again. I have "Animate windows when minimizing and maximizing" enabled, and I have never had an issue in the past - I can not find any solution online, and this only occurred post the Windows update with CoPilot (Preview). I have four monitors.

**Screenshots/Video**
Screenshots won't really help - whenever I click on an image for my wallpaper, nothing happens whatsoever. (Yes literally same issue as he's describing.)

**Desktop (please complete the following information):**
Edition	Windows 11 Pro
Version	22H2
Installed on	‎9/‎24/‎2022
OS build	22621.2361
Experience	Windows Feature Experience Pack 1000.22674.1000.0

**Additional context**
I've noticed myself that upon restart Lively entirely it works for awhile but after leaving my PC and coming back it's just the normal wallpaper again all of a sudden. 😭 Also SCREW Windows Hello for locking me out of my account and saying "Setup Pin" but clicking it did nothing. (After my idiotic self forgot to look up saving TPM settings / disabling Hello before flashing new BIOS update) We all really appreciate the great security features MS....... (Sarcasm intended.)

**Log file (Important)**
Attached.
[lively_log_20230929_172832.zip](https://github.com/rocksdanister/lively/files/12771998/lively_log_20230929_172832.zip)

**Comment by jtgslol** [comment] 2023-09-30 22:20
Exact same issue too

**Describe the bug**
After installing Win11, wallpaper will suddenly stop working, usually after going into sleep. It is sometimes fixed by reinstalling, but consistently stops working. Note that I do not have Copilot installed. Clicking on a wallpaper doesn't set it after this. 

**Screenshots/Video**
Screenshots won't really help - whenever I click on an image for my wallpaper, nothing happens whatsoever.

**Desktop (please complete the following information):**
Windows 11 Pro
Version 23H2
Installed on ‎8/25‎/‎2022
OS build 22621.2361
Experience Windows Feature Experience Pack 1000.22674.1000.0

**Log file (important)**
[lively_log_20230930_181444.zip](https://github.com/rocksdanister/lively/files/12775639/lively_log_20230930_181444.zip)

**Comment by nguyenhao2329** [comment] 2023-10-01 08:02
**DESCRIBE THE BUG:**
When I connect or disconnect the USB, the wallpaper is disabled. I have to quit the program and run it again. It's inconvenient.

**Desktop:**
Windows 11 Pro Insider Preview version
Version 22H2
Installed on October 1, 2023
OS build 23550.1000
Experience Windows Feature Experience Pack 1000.23550.1000.0

**Log file (important)**
[lively_log_20231001_143605.zip](https://github.com/rocksdanister/lively/files/12776658/lively_log_20231001_143605.zip)

**Comment by Styphoryte** [comment] 2023-10-01 14:45
Wait, so yours is it at least working? Say for example if you apply Lively
leave your PC for like 15 mins to 30 mins and come back is it still
working? I may try the Dev Preview just to get a lively working again, if that's the case. 😂 I don't mess with my USBs too often.

**Comment by rocksdanister** [comment] 2023-10-01 15:39
I don't support preview version, its constantly changing and it is very difficult to keep track.

**Comment by rocksdanister** [comment] 2023-10-01 15:47
@qCats Try turning off `GPU Decode` in video player and try to reproduce the issue, your issue looks like the video player crashing and unrelated to Windows update.

**Comment by jtgslol** [comment] 2023-10-01 17:11
Seems to have fixed the issue for now, thanks!

------- Original Message -------

**Comment by jtgslol** [comment] 2023-10-01 20:26
I've done a bit more testing, and this seems to have not fixed it. However, now sometimes it seems to fixes itself by just restarting the program. Very strange.

------- Original Message -------

**Comment by TheQuickFox** [comment] 2023-10-07 14:03
Same issue here. I tried uninstalling Lively 2 and downgrading to Lively 1.7.5.2 but it has the same problem.
So probably a bug or incompatibility with KB5030509 Windows 11 (22H2) configuration update - September 26, 2023

I can start the video wallpaper but after a while it stops playing and even after a reboot it does not restart.

**Comment by pstarSR** [comment] 2023-10-19 14:48
having the same issue, after the update. If I go play a game, when I come back the wallpaper app has failed ( but is still active in the tray and app is still open ) and I have a generic windows wallpaper. I click the app and it opens, but nothing changes if I click other wallpapers. I have to restart the app to get it back. Occasionally it will fail at startup also. Static image wallpapers here, no images or AI, or complexity. just high res png background.

win 11
[lively_log_20231019_074242.zip](https://github.com/rocksdanister/lively/files/13044060/lively_log_20231019_074242.zip)
log attached from this mornings failed launch.

**Closed as completed** 2023-10-24 07:23 UTC
Labels: bug, 22h2
