### ISSUE TITLE
Not compatible with `desktop-icon-toggle` program

### ISSUE THREAD

**Issue by dnknn** [rocksdanister/lively#687] opened 2021-08-23 19:33 UTC
> I don't know whose problem is because I don't understand the internal principles of the program.

If the two are used together, the desktop icons/folders cannot be `clicked`/`double-clicked` after using most of the live wallpapers except pure videos file wallpaper.

program is : Icons/folders on the desktop cannot be clicked/double-clicked(open)

I first reported the problem there 👉  https://github.com/hexandcube/desktop-icon-toggle/issues/2

If you are interested,  you can test to see what caused the problem.

**Comment by rocksdanister** [comment] 2021-08-23 19:38
This is a Lively issue https://github.com/rocksdanister/lively/issues/683

You can verify by turning off Wallpaper Input and see if it still happens.

**Comment by dnknn** [comment] 2021-08-23 19:52
> You can verify by turning off Wallpaper Input and see if it still happens.

@rocksdanister Thank you for your quick reply, after I tested it repeatedly for at least 5 times :

turning off Wallpaper Input : ✔️ **No** happens ✔️

It can finally solve the problem, but should improve it ?

> For example: If Web-JS `mouseEvent` , it can be optimized like this
```js

if (event.target===desktopIcon)		return;
		// more target method
	event.target.matches(`desktopIcon`)
	event.target.closest(`desktopIcon`)
	desktopIcon?.contains(event.target)
```

**Comment by rocksdanister** [comment] 2021-09-06 12:38
This is not a javascript issue, the problem is on my end.
I have a fix coming up in the beta channel in a few days.

Closing as duplicate https://github.com/rocksdanister/lively/issues/683

**Closed as completed by rocksdanister** 2021-09-06 12:38 UTC
Labels: bug, duplicate
