### ISSUE TITLE
Video wallpaper crash

### ISSUE THREAD

**Issue by unforgiving85** [rocksdanister/lively#362] opened 2021-03-18 10:17 UTC
**Before proceeding**
Check the Wiki:
https://github.com/rocksdanister/lively/wiki/Common-Problems
and Issues:
https://github.com/rocksdanister/lively/issues?q=is%3Aopen+is%3Aissue
to see if your problem is already addressed.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional context**

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) -> Misc. -> Log File
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`
[lively_log_20210318_111113.zip](https://github.com/rocksdanister/lively/files/6163177/lively_log_20210318_111113.zip)
[lively_log_20210318_111113.zip](https://github.com/rocksdanister/lively/files/6163178/lively_log_20210318_111113.zip)

**Comment by rocksdanister** [comment] 2021-03-18 10:53
```
Microsoft.Web.WebView2.Core.WebView2RuntimeNotFoundException: Couldn't find a compatible Webview2 Runtime..
```

**MS Edge** is not ready for use, switch web browser back to **CEF**:
`Lively settings -> Wallpaper -> Web Browser -> Engine -> CEF`

**Comment by unforgiving85** [comment] 2021-03-18 11:28
If this helps, you deserve a coffee ;)

**Comment by rocksdanister** [comment] 2021-03-18 14:27
**Fill the issue template:**

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional context**
Add any other context about the problem here.

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) -> Misc. -> Log File
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

**Comment by unforgiving85** [comment] 2021-03-18 14:35
Log files attached 
[lively_log_20210318_152454.zip](https://github.com/rocksdanister/lively/files/6164875/lively_log_20210318_152454.zip)

**Comment by rocksdanister** [comment] 2021-03-18 14:38
Latest logfile does not say much, something external in the system is causing the issue.

I need more details:
1. What wallpaper was running at the time?
2. Do you use any third party anti-virus software, if so which?
3. Do you use any desktop modification/overlay software?
4. Can you access Lively from system-tray menu after crash?

**Comment by unforgiving85** [comment] 2021-03-18 15:08
1. I have 2 monitors. First wallpaper - .mp4 file, 1920x1080p, 8,86MB. Second wallpaper - .mp4 file, 1280x720p, 2GB. But Lively crashes no matter which wallpaper is on, and that issue is from the beginning. 
2. Yes, AVG 21.1.3164 
3. Yes, Nexus Winstep 
4. Yes, I have Lively in the system-tray after the crash.

**Comment by unforgiving85** [comment] 2021-03-18 15:11
Additional: 
1. First, I was convinced that Lively crashes because of some other applications (Excel, Chrome, etc), but no - it crashes even when no other application is active. 
2. Approximately - 1 hour is the average time from start to crash.

**Comment by rocksdanister** [comment] 2021-03-18 15:13
I think its a combination of things:
1. The old gpu GT 710 could be the cause, disable/uncheck `GPU Decode` in `Lively settings -> Wallpaper -> Video` and try running a single video wallpaper on main screen to see if it crashes.
2. AVG is known to falsely flag some of Lively files, try adding an exception to Lively folder before attempting (1.)

**Comment by unforgiving85** [comment] 2021-03-18 15:39
1. Ok, I disabled GPU Decode
2. I allowed exceptions in AVG (folder and application). 

I will let you know. Thank you.

**Comment by unforgiving85** [comment] 2021-03-19 15:30
Crash again.
Log files attached. 
[lively_log_20210319_162811.zip](https://github.com/rocksdanister/lively/files/6172370/lively_log_20210319_162811.zip)

**Comment by rocksdanister** [comment] 2021-03-19 15:44
Run only single video wallpaper of 1080p/720p resolution and see if it crashes.

**Comment by rocksdanister** [comment] 2021-03-21 16:13
Unfortunately this does not look like the issue is with Lively but the video player/hardware/driver combination.
I am closing this since there is not much I can do to help from my end.
It will be better to enable logging `-log-file log.txt` in [mpv player](https://mpv.io/installation/) and report the bug [directly]( https://github.com/mpv-player/mpv) to the video player developers.

**Closed as completed by rocksdanister** 2021-03-21 16:13 UTC
Labels: bug, unrelated

**Comment by unforgiving85** [comment] 2021-03-22 07:22
I will try with different video players (mpv is current).

**Comment by unforgiving85** [comment] 2021-03-24 12:32
Unfortunately, still crashes... 
No use...

**Comment by unforgiving85** [comment] 2021-04-16 06:58
**I just want to say that you fixed the issue with the latest update.** 
When the wallpaper crashes, Lively will reactivate it after few seconds.
Well done. 
Do you have any donation ways except Paypal? :)
