### ISSUE TITLE
I can't open Lively and found this log file

### ISSUE THREAD

**Issue by GGCXD** [rocksdanister/lively#1459] opened 2022-11-15 18:48 UTC
[20221116_002103.txt](https://github.com/rocksdanister/lively/files/10015376/20221116_002103.txt)

**Comment by rocksdanister** [comment] 2022-11-15 18:51
Share the `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\UI` log folder.

**Comment by GGCXD** [comment] 2022-11-15 18:55
this? 
[20221116_002111.txt](https://github.com/rocksdanister/lively/files/10015404/20221116_002111.txt)

**Comment by rocksdanister** [comment] 2022-11-15 19:00
Looks like its duplicate of https://github.com/rocksdanister/lively/issues/1409

Currently nobody has provided required information: https://github.com/microsoft/WindowsAppSDK/issues/3037#issuecomment-1281612519

**Closed as completed by rocksdanister** 2022-11-15 19:00 UTC
Labels: duplicate
