### ISSUE TITLE
bilibili stream not working / 添加动态壁纸错误！

### ISSUE THREAD

**Issue by Aipeiju** [rocksdanister/lively#344] opened 2021-03-10 05:42 UTC
通过URL添加动态桌面背景报错。
![报错图片](https://user-images.githubusercontent.com/74533091/110581978-7573a700-81a6-11eb-9e29-f0e01f2c460d.png)

**Comment by rocksdanister** [comment] 2021-03-10 05:43
Share the logfile:
https://github.com/rocksdanister/lively/wiki/Common-Problems

**Comment by Aipeiju** [comment] 2021-03-10 06:00
[20210310_135445.txt](https://github.com/rocksdanister/lively/files/6113535/20210310_135445.txt)
日志文件

**Comment by rocksdanister** [comment] 2021-03-10 06:09
Looks like bilibili support is broken recently with the youtube-dl software I am using:
https://github.com/ytdl-org/youtube-dl/issues?q=is%3Aissue+is%3Aclosed+bilibili

The issue is marked as fixed, so next release of the youtube-dl software should have the fix.

**Comment by rocksdanister** [comment] 2021-03-14 07:43
Latest yt-dl update appears to fixed the issue:
https://github.com/ytdl-org/youtube-dl/releases/tag/2021.03.14
>[bilibili] Fix video info extraction

If you wish to manually update youtube-dl:
https://github.com/rocksdanister/lively/wiki/Streaming-Wallpaper

or use the beta version of Lively:
https://github.com/rocksdanister/lively-beta/releases/tag/v1.2.0.5

or you can wait 1~2 days for the next Lively stable update.

**Closed as completed by rocksdanister** 2021-03-14 07:43 UTC
Labels: bug
