### ISSUE TITLE
Show icons wallpaper issue

### ISSUE THREAD

**Issue by Dziksonn** [rocksdanister/lively#337] opened 2021-03-04 08:46 UTC
**Describe the bug**
Everything was working fine, before hiding icons. I'll desribe everything in reproduce section

**To Reproduce**
1. Turn off desktop icons
2. Turn on any lively wallpaper 
3. Then turn on icons
4. And now wallpaper for me doesn't work anymore with icons on, if i turn them off it works.

**Expected behavior**
I think there's no point of describing expected behavior, it should just work.

**Screenshots/Video**
Screenshot from developer menu if it can help
![image](https://user-images.githubusercontent.com/40899061/109935632-13aacd00-7cce-11eb-8ebb-b1095e2db6b7.png)

**Desktop (please complete the following information):**
 - OS: Win10 Home 1909

**Additional context**

**Log file**
[20210304_093346.txt](https://github.com/rocksdanister/lively/files/6082046/20210304_093346.txt)

(sorry if it isn't understandable but im not english native speaker. I can record video if it's needed to repair this issue)

**Comment by rocksdanister** [comment] 2021-03-06 16:30
I can't reproduce the error in my system, this is Likely some shell restart related https://github.com/rocksdanister/lively/issues/203 
Closing this one.

**Closed as completed by rocksdanister** 2021-03-06 16:30 UTC
Labels: bug, unable to reproduce
