### ISSUE TITLE
Customize Wallpaper can not be used with asecond monitor

### ISSUE THREAD

**Issue by TyWinkler** [rocksdanister/lively#21] opened 2020-02-22 18:19 UTC
Customize Wallpaper can not be used with a second monitor. The Customise Wallpaper button only brings up and modifies the wallpaper on a single monitor.

**Comment by rocksdanister** [comment] 2020-02-22 20:04
Is Wallpaper layout set to Span or Duplicate?
If not, did you not get a monitor selection dialogue?
(separate settings don't retain for same wallpaper which I am aware of, thats unrelated to this issue)

**Comment by rocksdanister** [comment] 2020-03-11 17:52
No steps provided, can't reproduce. I'm closing the issue for now. Make a new one with more details if you have the issue again.

If you are trying to customise the same wallpaper then it is already a known issue: https://github.com/rocksdanister/lively/issues/23

**Closed by rocksdanister** 2020-03-11 17:52 UTC
