### ISSUE TITLE
Multiple video loop.

### ISSUE THREAD

**Issue by Masterpiece-K** [rocksdanister/lively#190] opened 2020-11-09 04:28 UTC
I hope you can add a feature that let it play multiple videos in a loop.

**Comment by rocksdanister** [comment] 2020-11-09 05:00
Duplicate of this ?: https://github.com/rocksdanister/lively/issues/137

**Comment by Masterpiece-K** [comment] 2020-11-09 05:10
I mean I can put multiple wallpapers and have them looping around the desktop.

**Comment by rocksdanister** [comment] 2020-11-09 05:14
Yes, this will be possible in [Wallpaper Playlist](https://github.com/rocksdanister/lively/issues/137) once implemented.

Marking it as duplicate.

**Closed as completed by rocksdanister** 2020-11-09 05:14 UTC
Labels: duplicate, enhancement

**Comment by Masterpiece-K** [comment] 2020-11-09 05:16
OK，thank u
